
import { ref } from 'vue'
export const gameModeState = ref('1vs1') // Add state to track current gamemode
export const rankingModeState = ref('Quarter')
export const selectedAmount = ref('')
export const selectedOpponent = ref(null)
export const selectedTheme = ref(null)
export const rankingData = [
  {
    rank: 1,
    avatar: "src/assets/images/avatar/1avatar.png",
    pseudo: "BouattitNi",
    country: "Suisse",
    score: 42702,
  },
  {
    rank: 1,
    avatar: "src/assets/images/avatar/2avatar.png",
    pseudo: "mathancay",
    country: "Suisse",
    score: 42702,
  },
  {
    rank: 3,
    avatar: "src/assets/images/avatar/3avatar.png",
    pseudo: "CineCook",
    country: "Switzerland",
    score: 42701,
  },
  {
    rank: 4,
    avatar: "src/assets/images/avatar/4avatar.png",
    pseudo: "Stanzie",
    country: "Switzerland",
    score: 42641,
  },
  {
    rank: 5,
    avatar: "src/assets/images/avatar/5avatar.png",
    pseudo: "mam1lou",
    country: "Suisse",
    score: 42636,
  },
  {
    rank: 6,
    avatar: "src/assets/images/avatar/6avatar.png",
    pseudo: "Vicoco",
    country: "Suisse",
    score: 42633,
  },
  {
    rank: 7,
    avatar: "src/assets/images/avatar/7avatar.png",
    pseudo: "Maxouille",
    country: "Suisse",
    score: 42623,
  },
  {
    rank: 8,
    avatar: "src/assets/images/avatar/8avatar.png",
    pseudo: "Princess MOON",
    country: "South Korea",
    score: 42552,
  },
  {
    rank: 9,
    avatar: "src/assets/images/avatar/9avatar.png",
    pseudo: "Ki Tam",
    country: "Macao",
    score: 42518,
  },
  {
    rank: 10,
    avatar: "src/assets/images/avatar/10avatar.png",
    pseudo: "gg.mak",
    country: "Suisse",
    score: 42490,
  },
  {
    rank: 11,
    avatar: "src/assets/images/avatar/11avatar.png",
    pseudo: "HSM",
    country: "South Korea",
    score: 42475,
  },
  {
    rank: 12,
    avatar: "src/assets/images/avatar/12avatar.png",
    pseudo: "슈퍼오션",
    country: "South Korea",
    score: 42441,
  },
  {
    rank: 13,
    avatar: "src/assets/images/avatar/13avatar.png",
    pseudo: "lea2001",
    country: "Suisse",
    score: 42433,
  },
  {
    rank: 14,
    avatar: "src/assets/images/avatar/14avatar.png",
    pseudo: "GeorgeM",
    country: "Romania",
    score: 42414,
  },
  {
    rank: 15,
    avatar: "src/assets/images/avatar/15avatar.png",
    pseudo: "math.ildee",
    country: "Suisse",
    score: 42409,
  },
  {
    rank: 16,
    avatar: "src/assets/images/avatar/16avatar.png",
    pseudo: "Halldór",
    country: "Iceland",
    score: 42398,
  },
  {
    rank: 17,
    avatar: "src/assets/images/avatar/17avatar.png",
    pseudo: "Léa",
    country: "Suisse",
    score: 42390,
  },
  {
    rank: 18,
    avatar: "src/assets/images/avatar/18avatar.png",
    pseudo: "Toto",
    country: "France",
    score: 42380,
  },
  {
    rank: 19,
    avatar: "src/assets/images/avatar/19avatar.png",
    pseudo: "JohnDoe",
    country: "USA",
    score: 42370,
  },
  {
    rank: 20,
    avatar: "src/assets/images/avatar/20avatar.png",
    pseudo: "JaneSmith",
    country: "Canada",
    score: 42360,
  },
  {
    rank: 21,
    avatar: "src/assets/images/avatar/21avatar.png",
    pseudo: "PlayerOne",
    country: "Germany",
    score: 42350,
  },
  {
    rank: 22,
    avatar: "src/assets/images/avatar/22avatar.png",
    pseudo: "GamerGirl",
    country: "UK",
    score: 42340,
  },
  {
    rank: 23,
    avatar: "src/assets/images/avatar/23avatar.png",
    pseudo: "Speedster",
    country: "Italy",
    score: 42330,
  },
  {
    rank: 24,
    avatar: "src/assets/images/avatar/24avatar.png",
    pseudo: "Challenger",
    country: "Spain",
    score: 42320,
  },
    {
        rank: 25,
        avatar: "src/assets/images/avatar/25avatar.png",
        pseudo: "ElitePlayer",
        country: "Portugal",
        score: 42310,
    },
    {
        rank: 26,
        avatar: "src/assets/images/avatar/26avatar.png",
        pseudo: "ProGamer",
        country: "Netherlands",
        score: 42300,
    },
    {
        rank: 27,
        avatar: "src/assets/images/avatar/27avatar.png",
        pseudo: "MasterMind",
        country: "Belgium",
        score: 42290,
    },
    {
        rank: 28,
        avatar: "src/assets/images/avatar/28avatar.png",
        pseudo: "GameChanger",
        country: "Austria",
        score: 42280,
    },

]